chore: update workflows with pnpm

diff --git a/.github/workflows/nextjs.yml b/.github/workflows/nextjs.yml
--- a/.github/workflows/nextjs.yml
+++ b/.github/workflows/nextjs.yml
@@ -31,29 +31,29 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v4
-      - uses: pnpm/action-setup@v2 # 使用 pnpm
+      - uses: pnpm/action-setup@v4 # 使用 pnpm
       - name: Detect package manager
         id: detect-package-manager
         run: |
-          if [ -f "${{ github.workspace }}/pnpm-lock.yaml" ]; then
-            echo "manager=pnpm" >> $GITHUB_OUTPUT
-            echo "command=install" >> $GITHUB_OUTPUT
-            echo "runner=pnpm" >> $GITHUB_OUTPUT
-            exit 0
-          elif [ -f "${{ github.workspace }}/yarn.lock" ]; then
-            echo "manager=yarn" >> $GITHUB_OUTPUT
-            echo "command=install" >> $GITHUB_OUTPUT
-            echo "runner=yarn" >> $GITHUB_OUTPUT
-            exit 0
-          elif [ -f "${{ github.workspace }}/package.json" ]; then
-            echo "manager=npm" >> $GITHUB_OUTPUT
-            echo "command=ci" >> $GITHUB_OUTPUT
-            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
-            exit 0
-          else
-            echo "Unable to determine package manager"
-            exit 1
-          fi
+          # if [ -f "${{ github.workspace }}/pnpm-lock.yaml" ]; then
+          echo "manager=pnpm" >> $GITHUB_OUTPUT
+          echo "command=install" >> $GITHUB_OUTPUT
+          echo "runner=pnpm" >> $GITHUB_OUTPUT
+          exit 0
+          # elif [ -f "${{ github.workspace }}/yarn.lock" ]; then
+          #   echo "manager=yarn" >> $GITHUB_OUTPUT
+          #   echo "command=install" >> $GITHUB_OUTPUT
+          #   echo "runner=yarn" >> $GITHUB_OUTPUT
+          #   exit 0
+          # elif [ -f "${{ github.workspace }}/package.json" ]; then
+          #   echo "manager=npm" >> $GITHUB_OUTPUT
+          #   echo "command=ci" >> $GITHUB_OUTPUT
+          #   echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+          #   exit 0
+          # else
+          #   echo "Unable to determine package manager"
+          #   exit 1
+          # fi
       - name: Setup Node
         uses: actions/setup-node@v4
         with:
